### ISSUE TITLE
Create the Memory Bank

### ISSUE THREAD

**Issue by robotville** [AlmoonYsl/QTNet#11]
Hello, thanks very much for the wonderful paper and code.

I want to try using QTNet on my own custom dataset which is in NuScenes format. I think that if I generate the memory-bank for my own dataset I should be able to use QTNet for training and inference.

How do I generate the memory bank for my own dataset? 

Thanks very much for your help.

**Comment by AlmoonYsl** [comment]
> Hello, thanks very much for the wonderful paper and code.
> 
> I want to try using QTNet on my own custom dataset which is in NuScenes format. I think that if I generate the memory-bank for my own dataset I should be able to use QTNet for training and inference.
> 
> How do I generate the memory bank for my own dataset?
> 
> Thanks very much for your help.

Hi

Just save query features and detection results. Here is the code to serialize the results into files:

```query_feat = outs[0][0]['query_features'].squeeze(0).cpu().numpy()
 boxes = bbox_results[0]['boxes_3d'].tensor.cpu().numpy()
 scores = bbox_results[0]['scores_3d'].cpu().numpy()
 labels = bbox_results[0]['labels_3d'].cpu().numpy()
 result = dict(boxes=boxes, scores=scores, labels=labels)
 name = img_metas[0]['pts_filename'].split('/')[-1].split('.')[0] + '.bin'
 out_path_tokens = 'xxxx'
 np.save(out_path_tokens + name, query_feat)
 out_path_det = 'xxxx'
 pickle.dump(result, open(out_path_det + name, 'wb'))
```
