### ISSUE TITLE
multimodal training

### ISSUE THREAD

**Issue by wyd9697** [AlmoonYsl/QTNet#12]
Dear Author,

Thank you very much for your open-source work. I would like to ask how to perform multimodal training, as I did not find the corresponding use_camera section in the nuscenes_dataset_memory.py file. I look forward to your reply and once again, thank you.

Best regards

**Comment by AlmoonYsl** [comment]
> Dear Author,
> 
> Thank you very much for your open-source work. I would like to ask how to perform multimodal training, as I did not find the corresponding use_camera section in the nuscenes_dataset_memory.py file. I look forward to your reply and once again, thank you.
> 
> Best regards

QTNet only needs memory bank for training. Therefore, for multi-modal training it is only necessary to generate memory bank of the multi-modal detector.

**Comment by wyd9697** [comment]
Thank you for your reply. I would like to ask another question: how is the memory bank for the multimodal detector generated? Does it refer to any detection model and then the saved detection results? Additionally, after generating the memory bank, how do you perform multimodal training? Is it sufficient to just set use_camera to True?

Best regards,

**Comment by AlmoonYsl** [comment]
> Thank you for your reply. I would like to ask another question: how is the memory bank for the multimodal detector generated? Does it refer to any detection model and then the saved detection results? Additionally, after generating the memory bank, how do you perform multimodal training? Is it sufficient to just set use_camera to True?
> 
> Best regards,

Yes, you can save queries and detection results for any DETR-like 3D detectors. Only need to change memory bank, no other settings are required.

**Comment by wyd9697** [comment]
Got it, I'll give it a try. Thank you for your prompt response.

Best regards

**Comment by AlmoonYsl** [comment]
> Got it, I'll give it a try. Thank you for your prompt response.
> 
> Best regards

If you have any additional questions, please feel free to contact me.
