### ISSUE TITLE
Training environment

### ISSUE THREAD

**Issue by gubei1998** [AlmoonYsl/QTNet#7]
Hi author, what is the version of mmcv and mmdet you are using for training, I always encountered version conflict when configuring my environment!

**Comment by AlmoonYsl** [comment]
> Hi author, what is the version of mmcv and mmdet you are using for training, I always encountered version conflict when configuring my environment!

Hi.

Just keep it consistent with the environment of TransFusion.
mmcv-full==1.2.4, mmdet==2.10.0
